[tool.poetry]
name           = 'data_manipulation_utilities'
description    = 'Project storing utilities needed to reduce boilerplate code when analyzing data'
version        = 'v0.0.0'
readme         = 'README.md'
package-mode   = false

[tool.poetry.dependencies]
python         = '>=3.10, <3.13'
logzero        = '*'
PyYAML         = '*'
scipy          = '*'
awkward        = '*'
tqdm           = '*'
omegaconf      = '*'
toml           = '*'
uproot         = '*'
numpy          = '*'
matplotlib     = '*'
mplhep         = '*'
pandas         = '*'
tensorflow     = '*'
awkward-pandas = '*'
dask           = {version='*', extras=['dataframe','distributed']}
hist           = {version='*', extras=['plot']}

zfit           = {version='0.26.0', optional=true}
scikit-learn   = {version='*'     , optional=true}
joblib         = {version='*'     , optional=true}
optuna         = {version='*'     , optional=true}
pytest         = {version='*'     , optional=true}

[tool.poetry.extras]
fit  = ['zfit']
ml   = ['scikit-learn', 'joblib', 'optuna']
dev  = ['pytest']
# -----------------------------------------
# Setuptools
# -----------------------------------------
[project]
name            = 'data_manipulation_utilities'
description     = 'Project storing utilities needed to reduce boilerplate code when analyzing data'
readme          = 'README.md'
dynamic         = ['version']

[build-system]
requires      = ['setuptools>=61', 'setuptools_scm', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
version_scheme = 'guess-next-dev'
local_scheme   = 'no-local-version'

[project.scripts]
transform_text       ='dmu_scripts.text.transform_text:main'
coned                ='dmu_scripts.ssh.coned:main'
check_truth          ='dmu_scripts.physics.check_truth:main'
print_trees          ='dmu_scripts.rfile.print_trees:main'
compare_root_files   ='dmu_scripts.rfile.compare_root_files:main'
compare_classifiers  ='dmu_scripts.ml.compare_classifiers:main'

[tool.setuptools.package-data]
dmu_data=[
'rfile/*.yaml',
'text/*.txt',
'text/*.toml',
'ml/*/*.yaml',
'plotting/*/*.yaml',
'tests/*.txt',
'tests/*.yaml',
'tests/*.json',
'stats/parameters/data.yaml',
]

[tools.setuptools.packages.find]
where   = ['src']

[tool.setuptools]
script-files=['src/dmu_scripts/git/publish']
