[project]
name        = 'data_manipulation_utilities'
version     = '0.0.1'
dependencies= ['joblib', 'scikit-learn', 'toml', 'numpy', 'matplotlib', 'mplhep']

[project.optional-dependencies]
dev  = []

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
transform_text='dmu_scripts.text.transform_text:main'

[tool.setuptools.package-data]
dmu_data=['text/*.txt', 'text/*.toml', 'ml/*/*.yaml', 'plotting/*/*.yaml']

[tool.setuptools]
