[project]
name            = 'data_manipulation_utilities'
requires-python = ">=3.9,<3.13" #Tensorflow does not support anything above 3.12
version         = '0.2.7'
readme          = 'README.md'
dependencies= [
'logzero',
'PyYAML',
'scipy',
'awkward',
'tqdm',
'numpy',
'toml',
'uproot',
'tensorflow==2.18.0', # Use latest tensorflow allowed by zfit
'awkward-pandas', # Because DDFGetter might need to access files with jagged data?
'dask[dataframe,distributed]',
'numpy',
'matplotlib',
'mplhep',
'hist[plot]',
'pandas']

[project.optional-dependencies]
fit  = ['zfit']
ml   = ['scikit-learn', 'joblib', 'optuna']
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
transform_text       ='dmu_scripts.text.transform_text:main'
coned                ='dmu_scripts.ssh.coned:main'
check_truth          ='dmu_scripts.physics.check_truth:main'
print_trees          ='dmu_scripts.rfile.print_trees:main'
compare_root_files   ='dmu_scripts.rfile.compare_root_files:main'
compare_classifiers  ='dmu_scripts.ml.compare_classifiers:main'

[tool.setuptools.package-data]
dmu_data=[
'rfile/*.yaml',
'text/*.txt',
'text/*.toml',
'ml/*/*.yaml',
'plotting/*/*.yaml',
'tests/*.txt',
'tests/*.yaml',
'tests/*.json',
'stats/parameters/data.yaml',
]

[tool.setuptools]
script-files=['src/dmu_scripts/git/publish']
