[project]
name        = 'data_manipulation_utilities'
version     = '0.0.1'
dependencies= ['zfit', 'PyYAML', 'scipy', 'awkward', 'tqdm', 'joblib', 'scikit-learn', 'toml', 'numpy', 'matplotlib', 'mplhep', 'polars', 'pandas']

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
transform_text='dmu_scripts.text.transform_text:main'
coned         ='dmu_scripts.ssh.coned:main'

[tool.setuptools.package-data]
dmu_data=['text/*.txt', 'text/*.toml', 'ml/*/*.yaml', 'plotting/*/*.yaml']

[tool.setuptools]
